### ISSUE TITLE
Can't work in macOS Mojave(10.14)

### ISSUE THREAD

**Issue by hellomduo** [RayPS/Search-Engine-Switcher#1]
Can't work in macOS Mojave(10.14).
Because Safari tells me :
「Safari no longer supports the unsafe extension “Search Engine Switcher”」You can find newer extensions reviewed by Apple in the App Store or Safari Extensions Gallery.

see??
https://developer.apple.com/documentation/safariextensions

**Comment by RayPS** [comment]
Hi, i just updated this extension, can you try this version and tell me the result?

**Comment by hellomduo** [comment]
Sorry, this version still can't be used.

<img width="422" alt="2018-06-06 10 13 47" src="https://user-images.githubusercontent.com/37796453/41012081-871e7b1e-6972-11e8-8738-7fca3e58e313.png">

I have seen a lot of same issues ( include Tampermonkey extensions) in network.

maybe：
「Developer-signed Safari extensions are not supported in Safari 12. 」

more details：
https://developer.apple.com/documentation/safariextensions

 =.=!

**Comment by hellomduo** [comment]
sorry, this all issues by Apple.

but i find a website, it gives a way to solve.
https://georgegarside.com/blog/macos/install-any-safari-extension-macos-mojave/

thanks for you working
=.=!

**Comment by RayPS** [comment]
I will take a look after Mojave released

**Comment by RayPS** [comment]
The extension is now on Mac App Store and it should solve this issue.
https://itunes.apple.com/us/app/search-engine-switcher/id1398283493?ls=1&mt=8

**Comment by RayPS** [comment]
Hey, can you confirm it's fixed and close this issue?

**Comment by hellomduo** [comment]
yeah! i can find it in mac app store! thanks for your working!
